### ISSUE TITLE
2018 Copyright

### ISSUE THREAD

**Issue by carolight** [raywenderlich/MyRWTutorial#6]
Copyright in AppDelegate.swift and FILEHEADER macro are 2017

**Comment by sberrevoets** [comment]
It uses the `___YEAR___` directive so any new files should use 2018. Are you seeing different behavior?

**Comment by carolight** [comment]
When I created a new file in the project, it created the header with 2017. So I went into the plist and changed 2017 to 2018 and then it worked.

**Comment by carolight** [comment]
(that's `IDETemplateMacros.plist` in xcshareddata)

**Comment by sberrevoets** [comment]
Hmm, that file doesn't seem to have the string 2017 in it on master?

**Comment by carolight** [comment]
I downloaded the zip file as per instructions. If you then create a new file in that one, it comes out as 2017.
Download the zip file and right click `MyRWTutorial.xcodeproj` and choose *Show Package Contents*. In `xcshareddata`, edit `IDETemplateMacros.plist`. FILEHEADER is where the 2017 is.

**Comment by sberrevoets** [comment]
I don't see this 😐 Can you give a link to the zip file you're trying this with?

**Comment by carolight** [comment]
Let me try it again - you're making me doubt what I saw :)

**Comment by carolight** [comment]
1. https://github.com/raywenderlich/MyRWTutorial
2. click MyRWTutorial.zip
3. click Download
4. Open MyRWTutorial project
5. Create new Swift File
6. Header says "(c) 2017 Razeware LLC" - that data is coming out of IDETemplateMacros.plist

Also AppDelegate copyright is 2017

**Comment by carolight** [comment]
(btw the zip file is supposed to be free of git, and that's why I didn't clone the repository)

**Comment by sberrevoets** [comment]
Ahhh I see now. I was using GitHub's "download zip" button, not the checked-in .zip. Good catch!

**Comment by sberrevoets** [comment]
Just pushed an update, can you verify it's fixed now?

**Comment by carolight** [comment]
Yes - the new file is now 2018, but AppDelegate is still 2017

**Comment by sberrevoets** [comment]
Argh yes. Pushed another fix!

**Comment by carolight** [comment]
All good 👍

**Comment by sberrevoets** [comment]
Perfect, thanks for bringing this up!
